"""Adding Lecture data table

Revision ID: 82f7b5faf99f
Revises: 01e6d65bc07c
Create Date: 2023-07-04 15:00:38.094124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f7b5faf99f'
down_revision = '01e6d65bc07c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=False),
    sa.Column('topic_title', sa.String(length=100), nullable=False),
    sa.Column('topic_description', sa.String(length=5000), nullable=False),
    sa.Column('topic_keywords', sa.String(length=500), nullable=False),
    sa.Column('important_information', sa.String(length=5000), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['lecture.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lecture_data')
    # ### end Alembic commands ###
